spring.datasource.url=jdbc:postgresql://localhost:5432/placement_mgmt
spring.datasource.username=postgres
spring.datasource.password=Gaganau@2004
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081
